version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "8001:81"
    volumes:
      - "./confs/default.conf.template:/etc/nginx/conf.d/default.conf.template"
    environment:
      - FOLLOW_CHANNEL="general"